name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u naveen0317 --password-stdin

      - name: Build Backend Image
        working-directory: backend
        run: docker build -t naveen0317/mean-backend:latest .

      - name: Push Backend Image
        run: docker push naveen0317/mean-backend:latest

      - name: Build Frontend Image
        working-directory: frontend
        run: docker build -t naveen0317/mean-frontend:latest .

      - name: Push Frontend Image
        run: docker push naveen0317/mean-frontend:latest

